/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.11
 * Generated at: 2023-08-28 11:05:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.tech.blog.entity.SharePost;
import java.util.List;
import com.tech.blog.dao.UserDao;
import java.util.ArrayList;
import com.tech.blog.entity.Category;
import com.tech.blog.helper.DBConnection;
import java.sql.Connection;
import com.tech.blog.entity.AdminBean;
import java.util.ArrayList;
import com.tech.blog.entity.Category;
import com.tech.blog.helper.DBConnection;
import com.tech.blog.dao.UserDao;
import com.tech.blog.entity.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1692964200484L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1693113331702L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.tech.blog.dao.UserDao");
    _jspx_imports_classes.add("com.tech.blog.entity.SharePost");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("com.tech.blog.entity.User");
    _jspx_imports_classes.add("com.tech.blog.helper.DBConnection");
    _jspx_imports_classes.add("com.tech.blog.entity.Category");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.tech.blog.entity.AdminBean");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"errorpage.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Let's Talk</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Navabr -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".background {\r\n");
      out.write("	background: #00FFFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bg {\r\n");
      out.write("	background: #FF69B4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bg-color {\r\n");
      out.write("	background: #FF69B4;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");

User user = (User) session.getAttribute("user");
AdminBean admin = (AdminBean) session.getAttribute("admin");
response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- This is navbar -->\r\n");
      out.write("<nav class=\"navbar background sticky-top navbar-expand-lg\">\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<a class=\"navbar-brand text-dark fw-bold\" href=\"./\"><i\r\n");
      out.write("			class=\"fa-solid fa-user-ninja fa-flip\"></i> Let's Talk</a>\r\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("			data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("			aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("			aria-label=\"Toggle navigation\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("			<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("				<li class=\"nav-item\"><a\r\n");
      out.write("					class=\"nav-link active text-dark fw-bold\" aria-current=\"page\"\r\n");
      out.write("					href=\"./\">Home</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item dropdown\"><a\r\n");
      out.write("					class=\"nav-link dropdown-toggle text-dark fw-bold\" role=\"button\"\r\n");
      out.write("					data-bs-toggle=\"dropdown\" aria-expanded=\"false\"> Topic </a>\r\n");
      out.write("					<ul class=\"dropdown-menu\">\r\n");
      out.write("						<li><button class=\"dropdown-item\" onclick=\"getPost('All')\">All\r\n");
      out.write("								Programing</button></li>\r\n");
      out.write("						");

						UserDao userDao = new UserDao(DBConnection.createConnection());
						ArrayList<Category> list = userDao.getCategories();
						for (Category c : list) {
						
      out.write("\r\n");
      out.write("						<li><button class=\"dropdown-item\" id=\"");
      out.print(c.getCid());
      out.write("\"\r\n");
      out.write("								onclick=\"getPost('");
      out.print(c.getName());
      out.write("')\">");
      out.print(c.getName());
      out.write("</button></li>\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				");

				if (admin == null) {
				
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link text-dark fw-bold\"\r\n");
      out.write("					href=\"about.jsp\" aria-disabled=\"true\"><i\r\n");
      out.write("						class=\"fa-solid fa-address-card\"></i> About</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link text-dark fw-bold\"\r\n");
      out.write("					aria-disabled=\"true\" href=\"contactus.jsp\"><i\r\n");
      out.write("						class=\"fa-sharp fa-regular fa-id-badge\"></i> Contact Us</a></li>\r\n");
      out.write("				");

				}
				if (user != null) {
				
      out.write("\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					<button class=\"nav-link text-dark fw-bold\" aria-disabled=\"true\"\r\n");
      out.write("						data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">\r\n");
      out.write("						<img src=\"images/");
      out.print(user.getImage());
      out.write("\" class=\"img-fluid\" alt=\"\"\r\n");
      out.write("							style=\"width: 30px; height: 30px; border-radius: 50%;\">\r\n");
      out.write("					</button>\r\n");
      out.write("\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link text-dark fw-bold\"\r\n");
      out.write("					aria-disabled=\"true\" href=\"Logout\"><i\r\n");
      out.write("						class=\"fa-solid fa-right-to-bracket\"></i> Logout</a></li>\r\n");
      out.write("				");

				}
				if (admin != null) {
				
      out.write("\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					<button class=\"nav-link text-dark fw-bold\" aria-disabled=\"true\"\r\n");
      out.write("						data-bs-toggle=\"modal\" data-bs-target=\"#AdminModal\">\r\n");
      out.write("\r\n");
      out.write("						<i class=\"fa-solid fa-user-shield fa-bounce\"></i> Admin\r\n");
      out.write("					</button>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link text-dark fw-bold\"\r\n");
      out.write("					aria-disabled=\"true\" href=\"Logout\"><i\r\n");
      out.write("						class=\"fa-solid fa-right-to-bracket\"></i> Logout</a></li>\r\n");
      out.write("				");

				}
				if (user == null && admin == null) {
				
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link text-dark fw-bold\"\r\n");
      out.write("					aria-disabled=\"true\" href=\"login.jsp\"><i\r\n");
      out.write("						class=\"fa-solid fa-user fa-bounce\"></i> Login</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link text-dark fw-bold\"\r\n");
      out.write("					aria-disabled=\"true\" href=\"register.jsp\"><i\r\n");
      out.write("						class=\"fa-solid fa-right-to-bracket\"></i> Signup</a></li>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("			<form class=\"d-flex\" role=\"search\">\r\n");
      out.write("				<input class=\"form-control me-2\" type=\"search\"\r\n");
      out.write("					placeholder=\"Search Your Topic\" aria-label=\"Search\">\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- This is the popup for website -->\r\n");

if (user != null) {

      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\"\r\n");
      out.write("	aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("	<div class=\"modal-dialog\">\r\n");
      out.write("		<div class=\"modal-content Abhi\">\r\n");
      out.write("			<div class=\"modal-header bg-color text-light\">\r\n");
      out.write("				<h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">TechBlog</h1>\r\n");
      out.write("				<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("					aria-label=\"Close\"></button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"modal-body\">\r\n");
      out.write("				<div class=\"container-fluid\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"col-12 col-lg-12 col-md-12 d-flex justify-content-center\"\r\n");
      out.write("							style=\"height: 100px;\">\r\n");
      out.write("\r\n");
      out.write("							<img src=\"images/");
      out.print(user.getImage());
      out.write("\" alt=\"\" class=\"img-fluid\"\r\n");
      out.write("								style=\"border-radius: 50%; width: 100px\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"col-12 col-lg-12 col-md-12 d-flex justify-content-center\">\r\n");
      out.write("							<h5>");
      out.print(user.getName());
      out.write("</h5>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<table class=\"table\">\r\n");
      out.write("							<tbody>\r\n");
      out.write("\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th scope=\"col\">Email</th>\r\n");
      out.write("									<td>");
      out.print(user.getName());
      out.write("</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th scope=\"col\">Gender</th>\r\n");
      out.write("									<td>");
      out.print(user.getGender());
      out.write("</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th scope=\"col\">Joining Date</th>\r\n");
      out.write("									<td>");
      out.print(user.getDatetime());
      out.write("</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h4>About :</h4>\r\n");
      out.write("					<p>");
      out.print(user.getAbout());
      out.write("</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"modal-footer\">\r\n");
      out.write("				<button type=\"button\"\r\n");
      out.write("					class=\"btn bg-color text-light fw-bold Abhishek\">Edit</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"modal-content Tiwari\" style=\"display: none;\">\r\n");
      out.write("			<div class=\"modal-header bg-color text-light\">\r\n");
      out.write("				<h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">TechBlog</h1>\r\n");
      out.write("				<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("					aria-label=\"Close\"></button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<form action=\"Profilupdate\" method=\"post\" id=\"form\"\r\n");
      out.write("				enctype=\"multipart/form-data\">\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<div class=\"container-fluid\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"col-12 col-lg-12 col-md-12 d-flex justify-content-center\"\r\n");
      out.write("								style=\"height: 100px;\">\r\n");
      out.write("								<img src=\"images/");
      out.print(user.getImage());
      out.write("\" alt=\"\" class=\"img-fluid\"\r\n");
      out.write("									style=\"border-radius: 50%; width: 100px\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"col-12 col-lg-12 col-md-12 d-flex justify-content-center\">\r\n");
      out.write("								<h5>");
      out.print(user.getName());
      out.write("</h5>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3 row\">\r\n");
      out.write("						<label for=\"Name\" class=\"col-sm-2 col-form-label\">Username</label>\r\n");
      out.write("						<div class=\"col-sm-10\">\r\n");
      out.write("							<input type=\"text\" class=\"form-control\" name=\"name\"\r\n");
      out.write("								value=\"");
      out.print(user.getName());
      out.write("\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3 row\">\r\n");
      out.write("						<label for=\"Name\" class=\"col-sm-2 col-form-label\">Gender</label>\r\n");
      out.write("						<div class=\"col-sm-10\">\r\n");
      out.write("							<input type=\"text\" class=\"form-control\" name=\"gender\"\r\n");
      out.write("								value=\"");
      out.print(user.getGender());
      out.write("\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3 row\">\r\n");
      out.write("						<label for=\"inputPassword\" class=\"col-sm-2 col-form-label\">Password</label>\r\n");
      out.write("						<div class=\"col-sm-10\">\r\n");
      out.write("							<input type=\"password\" class=\"form-control\" id=\"inputPassword\"\r\n");
      out.write("								value=\"");
      out.print(user.getPassword());
      out.write("\" name=\"password\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"exampleFormControlTextarea1\" class=\"form-label\">About:</label>\r\n");
      out.write("						<textarea class=\"form-control\" id=\"exampleFormControlTextarea1\"\r\n");
      out.write("							rows=\"3\" name=\"about\">");
      out.print(user.getAbout());
      out.write("</textarea>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"input-group mb-3\">\r\n");
      out.write("						<label class=\"input-group-text\" for=\"inputGroupFile01\">New\r\n");
      out.write("							Profile Pic</label> <input type=\"file\" class=\"form-control\"\r\n");
      out.write("							id=\"inputGroupFile01\" name=\"img\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"submit\" class=\"btn bg-color\">Save changes</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");

}
if (admin != null) {

      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"AdminModal\" tabindex=\"-1\"\r\n");
      out.write("	aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("	<div class=\"modal-dialog\">\r\n");
      out.write("		<div class=\"modal-content Abhi\">\r\n");
      out.write("			<div class=\"modal-header bg-color text-light\">\r\n");
      out.write("				<h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">TechBlog</h1>\r\n");
      out.write("				<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("					aria-label=\"Close\"></button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"modal-body\">\r\n");
      out.write("				<div class=\"container-fluid\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"col-12 col-lg-12 col-md-12 d-flex justify-content-center\"\r\n");
      out.write("							style=\"height: 100px;\">\r\n");
      out.write("\r\n");
      out.write("							<img src=\"images/");
      out.print(admin.getAdminemail());
      out.write("\" alt=\"\"\r\n");
      out.write("								class=\"img-fluid\" style=\"border-radius: 50%; width: 100px\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"col-12 col-lg-12 col-md-12 d-flex justify-content-center\">\r\n");
      out.write("							<h5>");
      out.print(admin.getAdminname());
      out.write("</h5>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<table class=\"table\">\r\n");
      out.write("							<tbody>\r\n");
      out.write("\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th scope=\"col\">Adminid</th>\r\n");
      out.write("									<td>");
      out.print(admin.getAdminemail());
      out.write("</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th scope=\"col\">Gender</th>\r\n");
      out.write("									<td>");
      out.print(admin.getAdminid());
      out.write("</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th scope=\"col\">Joining Date</th>\r\n");
      out.write("									<td>");
      out.print(admin.getAdminname());
      out.write("</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"modal-footer\">\r\n");
      out.write("				<button type=\"button\"\r\n");
      out.write("					class=\"btn bg-color text-light fw-bold Abhishek\">Edit</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"modal-content Tiwari\" style=\"display: none;\">\r\n");
      out.write("			<div class=\"modal-header bg-color text-light\">\r\n");
      out.write("				<h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">TechBlog</h1>\r\n");
      out.write("				<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("					aria-label=\"Close\"></button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<form action=\"Profilupdate\" method=\"post\" id=\"form\"\r\n");
      out.write("				enctype=\"multipart/form-data\">\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<div class=\"container-fluid\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"col-12 col-lg-12 col-md-12 d-flex justify-content-center\"\r\n");
      out.write("								style=\"height: 100px;\">\r\n");
      out.write("								<img src=\"images/");
      out.print(admin.getAdminname());
      out.write("\" alt=\"\"\r\n");
      out.write("									class=\"img-fluid\" style=\"border-radius: 50%; width: 100px\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"col-12 col-lg-12 col-md-12 d-flex justify-content-center\">\r\n");
      out.write("								<h5>");
      out.print(admin.getAdminname());
      out.write("</h5>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3 row\">\r\n");
      out.write("						<label for=\"Name\" class=\"col-sm-2 col-form-label\">Admin\r\n");
      out.write("							Name</label>\r\n");
      out.write("						<div class=\"col-sm-10\">\r\n");
      out.write("							<input type=\"text\" class=\"form-control\" name=\"name\"\r\n");
      out.write("								value=\"");
      out.print(admin.getAdminname());
      out.write("\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3 row\">\r\n");
      out.write("						<label for=\"inputPassword\" class=\"col-sm-2 col-form-label\">Password</label>\r\n");
      out.write("						<div class=\"col-sm-10\">\r\n");
      out.write("							<input type=\"password\" class=\"form-control\" id=\"inputPassword\"\r\n");
      out.write("								value=\"");
      out.print(admin.getAdminname());
      out.write("\" name=\"password\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"input-group mb-3\">\r\n");
      out.write("						<label class=\"input-group-text\" for=\"inputGroupFile01\">New\r\n");
      out.write("							Profile Pic</label> <input type=\"file\" class=\"form-control\"\r\n");
      out.write("							id=\"inputGroupFile01\" name=\"img\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"submit\" class=\"btn bg-color\">Save changes</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");

}

      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- This is jquery -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.min.js\"\r\n");
      out.write("	integrity=\"sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- This is jquery code -->\r\n");
      out.write("<script>\r\n");
      out.write("$(()=>{\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	console.log(\"Abhishek Tiwari\");\r\n");
      out.write("	$(\"#form\").on(\"submit\",function(e)\r\n");
      out.write("	{\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		let form =new FormData(this);\r\n");
      out.write("		console.log(form);\r\n");
      out.write("		console.log(\"Hello\");\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url:\"Profilupdate\",\r\n");
      out.write("			type:\"POST\",\r\n");
      out.write("			data:form,\r\n");
      out.write("			success:function(data,textStatus,jqXHR)\r\n");
      out.write("			{\r\n");
      out.write("				if(data.trim()==='DONE')\r\n");
      out.write("					{\r\n");
      out.write("					swal({\r\n");
      out.write("						  title: \"Done\",\r\n");
      out.write("						  text: \"Update Successfully!\",\r\n");
      out.write("						  icon: \"success\",\r\n");
      out.write("						  button: \"OK\",\r\n");
      out.write("						})\r\n");
      out.write("						\r\n");
      out.write("					.then((value) => {\r\n");
      out.write("					  window.location=\"index\";\r\n");
      out.write("					});\r\n");
      out.write("					}\r\n");
      out.write("				else{\r\n");
      out.write("					swal({\r\n");
      out.write("						  title: \"Sorry\",\r\n");
      out.write("						  text: data.trim(),\r\n");
      out.write("						  icon: \"error\",\r\n");
      out.write("						  button: \"Try Again\",\r\n");
      out.write("						})\r\n");
      out.write("		            .then((value) => {\r\n");
      out.write("		            window.location = \"index\";\r\n");
      out.write("		        });\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("			error:function(jqXHR,textStatus,errorThrown)\r\n");
      out.write("			{\r\n");
      out.write("				console.log(\"Not Done\");\r\n");
      out.write("			},\r\n");
      out.write("			processData:false,\r\n");
      out.write("			contentType:false\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("    $('.Abhishek').click(function () {\r\n");
      out.write("        $(\".Abhi\").hide();\r\n");
      out.write("        $(\".Tiwari\").show();\r\n");
      out.write("    })\r\n");
      out.write("    $(\".btn-close\").click(()=>{\r\n");
      out.write("    	$(\".Abhi\").show();\r\n");
      out.write("        $(\".Tiwari\").hide();\r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- This is the home section -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- This is home page of web -->\r\n");
      out.write("	<section class=\"bg-color pb-5 pt-5  text-light\" id=\"HOME\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row mt-4\">\r\n");
      out.write("				<div class=\"col-lg-6 mt-lg-5 pt-lg-5\">\r\n");
      out.write("					<h1>\r\n");
      out.write("						Let's Talk About The<span class=\"text-dark fw-bold\">\r\n");
      out.write("							Programming</span>\r\n");
      out.write("					</h1>\r\n");
      out.write("					<p>A programming language is a system of notation for writing\r\n");
      out.write("						computer programs. Most programming languages are text-based\r\n");
      out.write("						formal languages, but they may also be graphical. They are a kind\r\n");
      out.write("						of computer language.</p>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						");

						if (user == null && admin == null) {
						
      out.write("\r\n");
      out.write("						<a class=\"btn btn-outline-light me-3\" href=\"register.jsp\"> <i\r\n");
      out.write("							class=\"fa-regular fa-circle-play fa-beat\"></i> Start! it's Free\r\n");
      out.write("						</a>\r\n");
      out.write("						<button class=\"btn btn-outline-light\"\r\n");
      out.write("							onclick=\"location='login.jsp'\">\r\n");
      out.write("							<i class=\"fa-solid fa-user fa-bounce\"></i> Login\r\n");
      out.write("						</button>\r\n");
      out.write("						");

						}
						if (user != null) {
						
      out.write("\r\n");
      out.write("						<a class=\"btn btn-outline-light me-3\" href=\"details.jsp\"> <i\r\n");
      out.write("							class=\"fa-solid fa-clock-rotate-left fa-beat-fade\"></i> Post\r\n");
      out.write("							Details\r\n");
      out.write("						</a>\r\n");
      out.write("						<button class=\"btn btn-outline-light\" data-bs-toggle=\"modal\"\r\n");
      out.write("							data-bs-target=\"#Post\">\r\n");
      out.write("							<i class=\"fa-solid fa-signs-post fa-shake\"></i> Post\r\n");
      out.write("						</button>\r\n");
      out.write("						");

						}
						if (admin != null) {
						
      out.write("<button class=\"btn btn-outline-light me-3\"\r\n");
      out.write("							data-bs-toggle=\"modal\" data-bs-target=\"#Delete\">\r\n");
      out.write("							<i class=\"fa-solid fa-trash-can fa-shake\"></i> Delete Topic\r\n");
      out.write("						</button>\r\n");
      out.write("						<button class=\"btn btn-outline-light\" data-bs-toggle=\"modal\"\r\n");
      out.write("							data-bs-target=\"#Topic\">\r\n");
      out.write("							<i class=\"fa-solid fa-plus fa-flip\"></i> Add Topic\r\n");
      out.write("						</button>\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-6 d-flex justify-content-center\">\r\n");
      out.write("					<img src=\"images/Programing.png\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- This is the all post -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- This is all the post -->\r\n");
      out.write("	<section id=\"home\" class=\"background\">\r\n");
      out.write("		<div class=\"container pt-3 pb-3 d-flex justify-content-center\">\r\n");
      out.write("			<h1 id=\"progrmas\">View Post</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container-fluid text-center\" id=\"loader\">\r\n");
      out.write("			<i class=\"fa-solid fa-arrows-rotate fa-spin fa-2xl\"></i>\r\n");
      out.write("			<p>Loading.....</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"container-fluid\" id=\"post-container\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- THis is popups for share the post -->\r\n");
      out.write("	<section>\r\n");
      out.write("		<div class=\"modal fade\" id=\"Post\" tabindex=\"-1\"\r\n");
      out.write("			aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("			<div class=\"modal-dialog\">\r\n");
      out.write("				<div class=\"modal-content\">\r\n");
      out.write("					<div class=\"modal-header bg-color text-light\">\r\n");
      out.write("						<h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Share\r\n");
      out.write("							Your Knowladge</h1>\r\n");
      out.write("						<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("							aria-label=\"Close\"></button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<form action=\"PostShare\" method=\"post\" id=\"post\"\r\n");
      out.write("						enctype=\"multipart/form-data\">\r\n");
      out.write("						<div class=\"modal-body\">\r\n");
      out.write("							<div class=\"mb-3\">\r\n");
      out.write("								<select class=\"form-select form-select-sm\" name=\"cid\"\r\n");
      out.write("									aria-label=\"Small select example\" id=\"select\">\r\n");
      out.write("									<option selected disabled>Selcet Your Category..</option>\r\n");
      out.write("									");

									for (Category c : list) {
									
      out.write("\r\n");
      out.write("									<option value=\"");
      out.print(c.getCid());
      out.write("\">\r\n");
      out.write("										");
      out.print(c.getName());
      out.write("\r\n");
      out.write("									</option>\r\n");
      out.write("									");

									}
									
      out.write("\r\n");
      out.write("								</select> <input type=\"hidden\" name=\"categori\" id=\"categori\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"mb-3\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" name=\"tittle\"\r\n");
      out.write("									id=\"exampleFormControlInput1\" placeholder=\"Enter Your Tittle\"\r\n");
      out.write("									required>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"mb-3\">\r\n");
      out.write("								<textarea class=\"form-control\" id=\"exampleFormControlTextarea1\"\r\n");
      out.write("									name=\"content\" rows=\"3\" placeholder=\"Enter Your Content\"></textarea>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"mb-3\">\r\n");
      out.write("								<textarea class=\"form-control\" id=\"exampleFormControlTextarea1\"\r\n");
      out.write("									name=\"program\" rows=\"3\"\r\n");
      out.write("									placeholder=\"Enter Your Program (if any)\"></textarea>\r\n");
      out.write("							</div>\r\n");
      out.write("							<p class=\"mb-1\">Select Your Post Pic..</p>\r\n");
      out.write("							<div class=\"input-group mb-3\">\r\n");
      out.write("								<input type=\"file\" class=\"form-control\" id=\"inputGroupFile01\"\r\n");
      out.write("									name=\"img\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"modal-footer\">\r\n");
      out.write("							<button type=\"submit\" class=\"btn bg-color text-dark\">POST</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"modal fade\" id=\"Topic\" tabindex=\"-1\"\r\n");
      out.write("			aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("			<div class=\"modal-dialog\">\r\n");
      out.write("				<div class=\"modal-content\">\r\n");
      out.write("					<div class=\"modal-header bg-color text-light\">\r\n");
      out.write("						<h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Add Your\r\n");
      out.write("							Topic</h1>\r\n");
      out.write("						<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("							aria-label=\"Close\"></button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<form action=\"AddTopic\" method=\"post\" id=\"AddTopic\"\r\n");
      out.write("						enctype=\"multipart/form-data\">\r\n");
      out.write("						<div class=\"modal-body\">\r\n");
      out.write("							<div class=\"mb-3\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" name=\"category\"\r\n");
      out.write("									id=\"exampleFormControlInput1\" placeholder=\"Enter Your Category\"\r\n");
      out.write("									required>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"mb-3\">\r\n");
      out.write("								<textarea class=\"form-control\" id=\"exampleFormControlTextarea1\"\r\n");
      out.write("									maxlength=\"250\" name=\"desc\" rows=\"3\"\r\n");
      out.write("									placeholder=\"Add Some Description\"></textarea>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"modal-footer\">\r\n");
      out.write("							<button type=\"submit\" class=\"btn bg-color text-dark\">Add</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"modal fade\" id=\"Delete\" tabindex=\"-1\"\r\n");
      out.write("			aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("			<div class=\"modal-dialog\">\r\n");
      out.write("				<div class=\"modal-content\">\r\n");
      out.write("					<div class=\"modal-header bg-color text-light\">\r\n");
      out.write("						<h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Delete\r\n");
      out.write("							Your Topic</h1>\r\n");
      out.write("						<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("							aria-label=\"Close\"></button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<form action=\"DeleteTopic\" method=\"post\" id=\"DeleteTopic\"\r\n");
      out.write("						enctype=\"multipart/form-data\">\r\n");
      out.write("						<div class=\"modal-body\">\r\n");
      out.write("							<div class=\"mb-3\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" name=\"category\"\r\n");
      out.write("									id=\"exampleFormControlInput1\" placeholder=\"Enter Your Topic\"\r\n");
      out.write("									required>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"modal-footer\">\r\n");
      out.write("							<button type=\"submit\" class=\"btn bg-color text-dark\">Delete</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"bg  pt-4 mt-auto\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-6 col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("				<h5 class=\"text-light\">ADDRESS</h5>\r\n");
      out.write("				<p class=\"m-0 text-light\">\r\n");
      out.write("					<i class=\"fa-solid fa-location-dot\"></i> Centurion Univercity\r\n");
      out.write("				</p>\r\n");
      out.write("				<p class=\"text-light\">Centurion Univercity</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-6 col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("				<h5 class=\"text-light\">ADDRESS</h5>\r\n");
      out.write("				<p class=\"m-0 text-light\">\r\n");
      out.write("					<i class=\"fa-solid fa-location-dot\"></i> Centurion Univercity\r\n");
      out.write("				</p>\r\n");
      out.write("				<p class=\"text-light\">Centurion Univercity</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-6 col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("				<h5 class=\"text-light\">ADDRESS</h5>\r\n");
      out.write("				<p class=\"m-0 text-light\">\r\n");
      out.write("					<i class=\"fa-solid fa-location-dot\"></i> Centurion Univercity\r\n");
      out.write("				</p>\r\n");
      out.write("				<p class=\"text-light\">Centurion Univercity</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-6 col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("				<h5 class=\"text-light\">ADDRESS</h5>\r\n");
      out.write("				<p class=\"m-0 text-light\">\r\n");
      out.write("					<i class=\"fa-solid fa-location-dot\"></i> Centurion Univercity\r\n");
      out.write("				</p>\r\n");
      out.write("				<p class=\"text-light\">Centurion Univercity</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<p>\r\n");
      out.write("			<a href=\"adminlogin.jsp\"\r\n");
      out.write("				class=\"link-light link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover\">Admin</a>\r\n");
      out.write("		</p>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"d-flex justify-content-center p-4 bg-warning\">This\r\n");
      out.write("		Website Fully Made By Abhishek Tiwari</div>\r\n");
      out.write("</section>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<!-- This is my all js code -->\r\n");
      out.write("<script>\r\n");
      out.write("$(()=>{	\r\n");
      out.write("	\r\n");
      out.write("	$(document).ready(function () {\r\n");
      out.write("	    $(\"#select\").on(\"change\", function () {\r\n");
      out.write("	        var selectedText = $(this).find(\"option:selected\").text();\r\n");
      out.write("\r\n");
      out.write("	        $(\"#categori\").val(selectedText);\r\n");
      out.write("	    });\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	console.log(\"This is for post the information of program\");\r\n");
      out.write("	$(\"#post\").on(\"submit\",function(e){\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		let form=new FormData(this);\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url:\"PostShare\",\r\n");
      out.write("			type:\"POST\",\r\n");
      out.write("			data:form,\r\n");
      out.write("			success:function(data,textStatus,jqXHR)\r\n");
      out.write("			{\r\n");
      out.write("				if(data.trim()==='DONE')\r\n");
      out.write("				{\r\n");
      out.write("				swal({\r\n");
      out.write("					  title: \"Done\",\r\n");
      out.write("					  text: \"Post Successfully!\",\r\n");
      out.write("					  icon: \"success\",\r\n");
      out.write("					  button: \"OK\",\r\n");
      out.write("					})\r\n");
      out.write("					\r\n");
      out.write("				.then((value) => {\r\n");
      out.write("				  window.location=\"index\";\r\n");
      out.write("				});\r\n");
      out.write("				}\r\n");
      out.write("			else{\r\n");
      out.write("				swal({\r\n");
      out.write("					  title: \"Sorry\",\r\n");
      out.write("					  text: data.trim(),\r\n");
      out.write("					  icon: \"error\",\r\n");
      out.write("					  button: \"Try Again\",\r\n");
      out.write("					})\r\n");
      out.write("	            .then((value) => {\r\n");
      out.write("	            window.location = \"index\";\r\n");
      out.write("	        });\r\n");
      out.write("			}\r\n");
      out.write("			},\r\n");
      out.write("			error:function(jqxhr,textStatus,errorThrown)\r\n");
      out.write("			{\r\n");
      out.write("				console.log(\"not\");\r\n");
      out.write("			},\r\n");
      out.write("			processData:false,\r\n");
      out.write("			contentType:false\r\n");
      out.write("		})\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	$(\"#AddTopic\").on(\"submit\",function(e){\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		let form=new FormData(this);\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url:\"AddTopic\",\r\n");
      out.write("			type:\"POST\",\r\n");
      out.write("			data:form,\r\n");
      out.write("			success:function(data,textStatus,jqXHR)\r\n");
      out.write("			{\r\n");
      out.write("				if(data.trim()==='DONE')\r\n");
      out.write("				{\r\n");
      out.write("				swal({\r\n");
      out.write("					  title: \"Done\",\r\n");
      out.write("					  text: \"Added Successfully!\",\r\n");
      out.write("					  icon: \"success\",\r\n");
      out.write("					  button: \"OK\",\r\n");
      out.write("					})\r\n");
      out.write("					\r\n");
      out.write("				.then((value) => {\r\n");
      out.write("				  window.location=\"index\";\r\n");
      out.write("				});\r\n");
      out.write("				}\r\n");
      out.write("			else{\r\n");
      out.write("				swal({\r\n");
      out.write("					  title: \"Sorry\",\r\n");
      out.write("					  text: data.trim(),\r\n");
      out.write("					  icon: \"error\",\r\n");
      out.write("					  button: \"Try Again\",\r\n");
      out.write("					})\r\n");
      out.write("	            .then((value) => {\r\n");
      out.write("	            window.location = \"index\";\r\n");
      out.write("	        });\r\n");
      out.write("			}\r\n");
      out.write("			},\r\n");
      out.write("			error:function(jqxhr,textStatus,errorThrown)\r\n");
      out.write("			{\r\n");
      out.write("				console.log(\"not\");\r\n");
      out.write("			},\r\n");
      out.write("			processData:false,\r\n");
      out.write("			contentType:false\r\n");
      out.write("		})\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	$(\"#DeleteTopic\").on(\"submit\",function(e){\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		let form=new FormData(this);\r\n");
      out.write("		swal({\r\n");
      out.write("	        title: \"Are you sure?\",\r\n");
      out.write("	        text: \"Once deleted, You Will Not Be Able To Recover This Topic!\",\r\n");
      out.write("	        icon: \"warning\",\r\n");
      out.write("	        buttons: true,\r\n");
      out.write("	        dangerMode: true,\r\n");
      out.write("	    })\r\n");
      out.write("	        .then((willDelete) => {\r\n");
      out.write("	            if (willDelete) {\r\n");
      out.write("	            	$.ajax({\r\n");
      out.write("	        			url:\"DeleteTopic\",\r\n");
      out.write("	        			type:\"POST\",\r\n");
      out.write("	        			data:form,\r\n");
      out.write("	        			success:function(data,textStatus,jqXHR)\r\n");
      out.write("	        			{\r\n");
      out.write("	        				if(data.trim()==='DONE')\r\n");
      out.write("	        				{\r\n");
      out.write("	        				swal({\r\n");
      out.write("	        					  title: \"Done\",\r\n");
      out.write("	        					  text: \"Delete Successfully!\",\r\n");
      out.write("	        					  icon: \"success\",\r\n");
      out.write("	        					  button: \"OK\",\r\n");
      out.write("	        					})\r\n");
      out.write("	        					\r\n");
      out.write("	        				.then((value) => {\r\n");
      out.write("	        				  window.location=\"index\";\r\n");
      out.write("	        				});\r\n");
      out.write("	        				}\r\n");
      out.write("	        			else{\r\n");
      out.write("	        				swal({\r\n");
      out.write("	        					  title: \"Sorry\",\r\n");
      out.write("	        					  text: data.trim(),\r\n");
      out.write("	        					  icon: \"error\",\r\n");
      out.write("	        					  button: \"Try Again\",\r\n");
      out.write("	        					})\r\n");
      out.write("	        	            .then((value) => {\r\n");
      out.write("	        	            window.location = \"index\";\r\n");
      out.write("	        	        });\r\n");
      out.write("	        			}\r\n");
      out.write("	        			},\r\n");
      out.write("	        			error:function(jqxhr,textStatus,errorThrown)\r\n");
      out.write("	        			{\r\n");
      out.write("	        				console.log(\"not\");\r\n");
      out.write("	        			},\r\n");
      out.write("	        			processData:false,\r\n");
      out.write("	        			contentType:false\r\n");
      out.write("	        		})\r\n");
      out.write("	                swal(\"Poof! Your imaginary file has been deleted!\", {\r\n");
      out.write("	                    icon: \"success\",\r\n");
      out.write("	                });\r\n");
      out.write("	            } else {\r\n");
      out.write("	                swal(\"Your Topic is safe!\",{\r\n");
      out.write("	                	 icon: \"success\",\r\n");
      out.write("	                }).then((value) => {\r\n");
      out.write("        	            window.location = \"index\";\r\n");
      out.write("        	        });\r\n");
      out.write("	            }\r\n");
      out.write("	        });\r\n");
      out.write("		\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("console.log(\"This is request to fetch data dynamically\");\r\n");
      out.write("function getPost(catid){\r\n");
      out.write("$.ajax({\r\n");
      out.write("	url:\"post.jsp\",\r\n");
      out.write("	data:{cid:catid},\r\n");
      out.write("	success:function(data,textStatus, jqxhr){\r\n");
      out.write("		$(\"#post-container\").html(data);\r\n");
      out.write("		$(\"#loader\").hide();\r\n");
      out.write("	}\r\n");
      out.write("})}\r\n");
      out.write("getPost('All');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("console.log(\"This is for When i click the dwopdown according to that my header show\");\r\n");
      out.write("let btntag = Array.from(document.getElementsByClassName(\"dropdown-item\"));\r\n");
      out.write("let h1tag = document.getElementById(\"progrmas\");\r\n");
      out.write("btntag.forEach(function (element, index, btntag) {\r\n");
      out.write("    element.addEventListener(\"click\", function () {\r\n");
      out.write("        // console.log(element.textContent);\r\n");
      out.write("        let str = element.textContent;\r\n");
      out.write("        console.log(str);\r\n");
      out.write("        h1tag.textContent = str;\r\n");
      out.write("    })\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("console.log(\"This is for search the special program\");\r\n");
      out.write("let inputTag = document.getElementsByTagName(\"input\")[0];\r\n");
      out.write("\r\n");
      out.write("    inputTag.addEventListener(\"input\", () => {\r\n");
      out.write("        let inputTagVal = inputTag.value.toLowerCase().trim();\r\n");
      out.write("        let colClass = Array.from(document.getElementsByClassName(\"abhi\"));\r\n");
      out.write("        colClass.forEach(function (element) {\r\n");
      out.write("            let h5Tag = element.getElementsByTagName(\"b\")[0].textContent.toLowerCase();\r\n");
      out.write("            if (h5Tag.includes(inputTagVal)) {\r\n");
      out.write("                element.classList.remove(\"d-none\");\r\n");
      out.write("            } else {\r\n");
      out.write("                element.classList.add(\"d-none\");\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
